#!/bin/bash

ghcpath="/usr/local/bin"
benchpath="/home/rio/HaskellSTMbenchmark"

ghcoptions="--make -O -threaded -fglasgow-exts"

#clean .o's,  prepare directories

cd $benchpath/1-SharedInt/
              rm *.o

cd $benchpath/2-LL/
	      find . -name '*.o' -exec rm {} \;

cd $benchpath/3-BT/
	      find . -name '*.o' -exec rm {} \;

cd $benchpath/4-HashTable/
	      find . -name '*.o' -exec rm {} \;

cd $benchpath/5-TCache/
	      rm Main
	      find . -name '*.o' -exec rm {} \;
	      find . -name '*.hi' -exec rm {} \;

cd $benchpath/6-ParallelSudoku/
              rm *.o

cd $benchpath/7-CCHR/
              find . -name '*.o' -exec rm {} \;

cd $benchpath/8-spi/
	      find . -name '*.o' -exec rm {} \;

# COMPILE

echo SI
cd $benchpath/1-SharedInt
$ghcpath/ghc Main.hs $ghcoptions 

echo LL
cd $benchpath/2-LL/withoutUnread
$ghcpath/ghc Main.hs $ghcoptions

echo BT
cd $benchpath/3-BT/withoutUnread
$ghcpath/ghc Main.hs $ghcoptions

echo HT
cd $benchpath/4-HashTable
$ghcpath/ghc Main.hs $ghcoptions

echo TCache
cd $benchpath/5-TCache
$ghcpath/ghc Main.hs --make -threaded -fglasgow-exts #does not work with -O. nor with ghc-6.10

echo Sud
cd $benchpath/6-ParallelSudoku
$ghcpath/ghc Main.hs $ghcoptions

echo CCHR
cd $benchpath/7-CCHR
for program in "Sudoku" "Gcd" "Unionfind" "Blockworld" "Prime"
  do
    $ghcpath/ghc $program.hs --make -threaded -fglasgow-exts # -O does not work here either
  done

echo SPI
cd $benchpath/8-spi/parallel/
$ghcpath/ghc Main.hs $ghcoptions
