#!/bin/bash
for numOp in 8000 
do
   for numThreads in 1 2 4 8
   do
        for lengthList in 10 100 1000
		do
		for((i=1;$i<=5;i=$(($i+1))));
			do
			ops=$(($numOp/$numThreads))
			./Main $ops $lengthList $numThreads 1 +RTS -N$numThreads -RTS | tee -a "./results OPS$numOp ELEMS$lengthList THREADS$numThreads"
			done			
		done
   done
done
