#!/bin/bash
rm *.o *.hi
rm CCHR/*.o *.hi
rm CCHRCompiler/*.o *.hi
rm CCHR/Control/*.o *.hi

for program in "Sudoku" "Gcd" "Unionfind" "Blockworld" "Prime"
	do
		ghc --make $program.hs -fglasgow-exts -threaded -fno-warn-tabs
	done